fruits = ["apple", "kiwi", "cherry"]
fruits.append("orange")
print(fruits)
fruits.insert(1, "mango")
print(fruits)
fruits.remove("apple")
print(fruits)
fruits.pop()
print(fruits)
fruits.clear()
print(fruits)